import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-3xl underline">
          Willkommen bei Munchkin PlayerTable
        </h1>
        <div>
          <h2 className='text-2xl font-bold'>aktuelle Spieler</h2>
          <table className="table-fixed border-collapse border border-slate-400">
            <thead>
              <tr>
                <th className='border border-slate-300'>Name</th>
                <th className='border border-slate-300'>Level</th>
                <th className='border border-slate-300'>Attack</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className='border border-slate-300'>Marc</td>
                <td className='border border-slate-300'>1</td>
                <td className='border border-slate-300'>1</td>
              </tr>
            </tbody>
          </table>
        </div>
      </main>
    </>
  )
}
